// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lnfqbnabwhgqcnaorjtt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxuZnFibmFid2hncWNuYW9yanR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2OTk5MzksImV4cCI6MjA3MDI3NTkzOX0.aEGmDg_-SJ6W_yTMqRsRcx4Q6aweez5uk3dt1ZzDH7U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});